version: '3.1'

services:

  db:
    image: postgres
    restart: always
    env_file: .env


  app:
    container_name: app
    build: .
    volumes:
      - .:/app:rw
    ports:
      - 5432:5432
    command: "flask run -h 0.0.0.0 -p 5000"
    env_file: .env
    restart: always
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080